# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choco_name', models.CharField(max_length=100)),
                ('choco_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('choco_gt_20_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('choco_gt_60_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('choco_pic', models.CharField(max_length=100)),
                ('choco_dir', models.CharField(max_length=100)),
                ('choco_art', models.CharField(max_length=100)),
                ('choco_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choco_size', models.CharField(max_length=11)),
                ('choco_weight', models.PositiveSmallIntegerField()),
                ('choco_quantity_in_box', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_note', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_conf', models.CharField(max_length=100)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='assortment',
            name='choco_config',
            field=models.ManyToManyField(to='choco.Configuration'),
        ),
    ]
