# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
