# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='choco_art',
            field=models.CharField(max_length=100),
        ),
    ]
