# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='quantity',
        ),
    ]
