# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choco_size', models.CharField(max_length=11)),
                ('choco_weight', models.PositiveSmallIntegerField()),
                ('choco_quantity_in_box', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='assortment',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='assortment',
            name='choco_quantity_in_box',
        ),
        migrations.RemoveField(
            model_name='assortment',
            name='choco_size',
        ),
        migrations.RemoveField(
            model_name='assortment',
            name='choco_weight',
        ),
        migrations.AddField(
            model_name='assortment',
            name='choco_config',
            field=models.ManyToManyField(to='choco.Configuration'),
        ),
    ]
