# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0002_auto_20181003_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_note', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_conf', models.CharField(max_length=100)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
