# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0002_remove_configuration_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
