# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-18 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0003_assortment_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='choco.Subcategory'),
        ),
    ]
