# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0003_auto_20181112_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
