# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-01 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0004_auto_20190318_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
